=== molnar75/xml/xml_beadando/beadando/megrendeles.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT nyilvantartas (etelek,ettermek,dolgozok,rendezvenyek,megrendelesek)>

<!ELEMENT etelek (etel*)>
<!ELEMENT etel (nev, ar, allergenek, leiras)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT ar (#PCDATA)>
<!ELEMENT allergenek (allergen)>
<!ELEMENT allergen (#PCDATA)>
<!ATTLIST allergen aid ID #REQUIRED>
<!ELEMENT leiras (#PCDATA)>
<!ATTLIST etel etid ID #REQUIRED>

<!ELEMENT ettermek (etterem*)>

<!ELEMENT etterem (nev, weblap, minosites, telefonszam)>
<!ELEMENT weblap (#PCDATA)>
<!ELEMENT minosites (#PCDATA)>
<!ELEMENT telefonszam (#PCDATA)>
<!ATTLIST etterem eid ID #REQUIRED>

<!ELEMENT dolgozok (dolgozo*)>

<!ELEMENT dolgozo (nev, beosztas, cim, telefonszam)>
<!ELEMENT beosztas (#PCDATA)>
<!ELEMENT cim (irsz, varos, utca, hazszam)>
<!ELEMENT irsz (#PCDATA)>
<!ELEMENT utca (#PCDATA)>
<!ELEMENT hazszam (#PCDATA)>
<!ELEMENT varos (#PCDATA)>
<!ATTLIST dolgozo did ID #REQUIRED>


<!ELEMENT rendezvenyek (rendezveny*)>

<!ELEMENT rendezveny (idopont, cim)>
<!ELEMENT idopont (#PCDATA)>
<!ATTLIST rendezveny rid ID #REQUIRED>

<!ELEMENT megrendelesek (megrendeles*)>

<!ELEMENT megrendeles (ar)>
<!ATTLIST megrendeles etterem IDREF #REQUIRED>
<!ATTLIST megrendeles rendezveny IDREF #REQUIRED>

=== molnar75/xml/xml_beadando/beadando/megrendelesfromdtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nyilvantartas SYSTEM "megrendeles.dtd" >
<nyilvantartas>
  <etelek>
		<etel etid="et1">
			<nev>
				rantotta
			</nev>
			<ar>
				700
			</ar>
			<allergenek>
				<allergen aid="a1">
					tej
				</allergen>
			</allergenek>
			<leiras>
				Vajon uvegesre piritott hagyman megsutott tojas
			</leiras>
		</etel>
	</etelek>
  <ettermek>
		<etterem eid="e1">
			<nev>
				etterem
			</nev>
			<weblap>
				www.thisetterem.com
			</weblap>
			<minosites>
				****
			</minosites>
			<telefonszam>
				0670387625
			</telefonszam>
		</etterem>
	</ettermek>
  <dolgozok>
		<dolgozo did="d1">
			<nev>
				Dolgozo Valaki
			</nev>
			<beosztas>
				foszakacs
			</beosztas>
			<cim>
				<irsz>
					3580
				</irsz>
				<varos>
					Tiszaujvaros
				</varos>
				<utca>
					Szent Istvan ut
				</utca>
				<hazszam>
					30. 1/5.
				</hazszam>
			</cim>
			<telefonszam>
				067046573625
			</telefonszam>
		</dolgozo>
	</dolgozok>
  <rendezvenyek>
		<rendezveny rid="r1">
			<idopont>
				2019.04.28.
			</idopont>
			<cim>
				<irsz>
					3580
				</irsz>
				<varos>
					Tiszaujvaros
				</varos>
				<utca>
					Nagy Karoly ucta
				</utca>
				<hazszam>
					12.
				</hazszam>
			</cim>
		</rendezveny>
	</rendezvenyek>
  <megrendelesek>
		<megrendeles etterem="e1" rendezveny="r1">
			<ar>
				150000 Ft
			</ar>
		</megrendeles>
	</megrendelesek>
</nyilvantartas>
