=== molnar75/xml/xml_beadando/beadando_project/data/megrendeles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="nyilvantartas" type="nyilvantartasTipus"></xs:element>
    
    <xs:complexType name="nyilvantartasTipus">
    	<xs:sequence>
    		<xs:element name="ettermek" type="ettermekTipus"></xs:element>
    		<xs:element name="etelek" type="etelekTipus"></xs:element>
    		<xs:element name="dolgozok" type="dolgozokTipus"></xs:element>
    		<xs:element name="rendezvenyek" type="rendezvenyekTipus"></xs:element>
    		<xs:element name="megrendelesek" type="megrendelesekTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
	<!-- ettermek -->
    <xs:complexType name="ettermekTipus">
    	<xs:sequence>
    		<xs:element name="etterem" type="etteremTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="etteremTipus">
    	<xs:sequence>
    		<xs:element name="nev" type="xs:string"></xs:element>
    		<xs:element name="weblap" type="xs:string"></xs:element>
    		<xs:element name="minosites" type="xs:string"></xs:element>
    		<xs:element name="telefonszam" type="xs:string"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="eid" type="xs:int" use="required"/>
    </xs:complexType>
    
    <!-- etelek -->
    <xs:complexType name="etelekTipus">
    	<xs:sequence>
    		<xs:element name="etel" type="etelTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="etelTipus">
    	<xs:sequence>
    		<xs:element name="nev" type="xs:string"></xs:element>
    		<xs:element name="ar" type="xs:int"></xs:element>
    		<xs:element name="allergenek" type="allergenekTipus"></xs:element>
    		<xs:element name="leiras" type="xs:string"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="etid" type="xs:int" use="required"/>
    </xs:complexType>

	<!-- allergenek -->
    <xs:complexType name="allergenekTipus">
    	<xs:sequence>
    		<xs:element name="allergen" type="xs:string"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="aid" type="xs:int" use="required"/>
    </xs:complexType>
    

	<!-- dolgozok -->
    <xs:complexType name="dolgozokTipus">
    	<xs:sequence>
    		<xs:element name="dolgozo" type="dolgozoTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dolgozoTipus">
    	<xs:sequence>
	    	<xs:element name="nev" type="xs:string"></xs:element>
	   		<xs:element name="beosztas" type="xs:string"></xs:element>
	   		<xs:element name="cim" type="cimTipus"></xs:element>
	   		<xs:element name="telefonszam" type="xs:string"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="did" type="xs:int" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="cimTipus">
    	<xs:sequence>
	    	<xs:element name="irsz" type="xs:string"></xs:element>
	   		<xs:element name="varos" type="xs:string"></xs:element>
	   		<xs:element name="utca" type="xs:string"></xs:element>
	   		<xs:element name="hazszam" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
	<!-- rendezvenyek -->
	<xs:complexType name="rendezvenyekTipus">
    	<xs:sequence>
    		<xs:element name="rendezveny" type="rendezvenyTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="rendezvenyTipus">
    	<xs:sequence>
    		<xs:element name="idopont" type="xs:date"></xs:element>
    		<xs:element name="cim" type="cimTipus"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="rid" type="xs:int" use="required"/>
    </xs:complexType>

	<!-- megrendelesek -->
	<xs:complexType name="megrendelesekTipus">
    	<xs:sequence>
    		<xs:element name="megrendeles" type="megrendelesTipus"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="megrendelesTipus">
    	<xs:sequence>
    		<xs:element name="ar" type="xs:long"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="etterem" type="xs:int" use="required"/>
    	<xs:attribute name="rendezveny" type="xs:int" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== molnar75/xml/xml_beadando/beadando/megrendeles.xml
<?xml version="1.0" encoding="UTF-8"?>
<nyilvantartas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="megrendeles.xsd">
  <ettermek>
    <etterem eid="0">
      <nev>Arany Hollo</nev>
      <weblap>www.aranyhollo.hu</weblap>
      <minosites>****</minosites>
      <telefonszam>06703237436</telefonszam>
    </etterem>
  </ettermek>
  <etelek>
    <etel etid="0">
      <nev>Aranygaluska</nev>
      <ar>800</ar>
      <allergenek aid="0">
        <allergen>Tej</allergen>
      </allergenek>
      <leiras>Aranygaluska ahogy nagyszüleink készítették!</leiras>
    </etel>
  </etelek>
  <dolgozok>
    <dolgozo did="0">
      <nev>Szorgos János</nev>
      <beosztas>konyhafőnök</beosztas>
      <cim>
        <irsz>3580</irsz>
        <varos>Tiszaujvaros</varos>
        <utca>Szent István utca</utca>
        <hazszam>10.</hazszam>
      </cim>
      <telefonszam>06317564736</telefonszam>
    </dolgozo>
  </dolgozok>
  <rendezvenyek>
    <rendezveny rid="0">
      <idopont>2019-12-05</idopont>
      <cim>
        <irsz>3508</irsz>
        <varos>Hejőcsaba</varos>
        <utca>Gárdonyi út</utca>
        <hazszam>20.</hazszam>
      </cim>
    </rendezveny>
  </rendezvenyek>
  <megrendelesek>
    <megrendeles etterem="0" rendezveny="0">
      <ar>180000</ar>
    </megrendeles>
  </megrendelesek>
</nyilvantartas>
